this fix #69 : Cannot obtain text for binary file type : UNKNOWN
zalando/intellij-swagger pull request #77
Opened 2017-02-28 19:51 UTC by manuc66

2017-02-28 20:06 UTC, manuc66 commented
- fix the file extension checking
- ensure that FileContent are not considered as binary before trying to convert to PsiFile

2017-03-03 07:14 UTC, semonte requested changes
This is looking great, made a few comments. Once they are fixed, I will merge.

2017-03-03 07:14 UTC, semonte commented on src/main/java/org/zalando/intellij/swagger/file/FileDetector.java
> +        return FilenameUtils.isExtension(file.getName(), new String[]{"json", "yaml", "yml"});
We could create new constants for the types in https://github.com/zalando/intellij-swagger/blob/master/src/main/java/org/zalando/intellij/swagger/file/FileConstants.java and use them

2017-03-03 07:14 UTC, semonte commented on src/test/java/org/zalando/intellij/swagger/file/FileDetectorTest.java
> +    public void thatSimilarileExtensionAreNotSwaggerContentCompatible() throws Exception {
`thatSimilarileExtensionAreNotSwaggerContentCompatible` to `thatSimilarFileExtensionsAreNotSwaggerContentCompatible`

2017-03-06 07:05 UTC, semonte commented
@manuc66 The following tests fail:

```
org.zalando.intellij.swagger.file.FileDetectorTest > thatIsSwaggerYamlFileBasedOnFileName FAILED
    java.lang.AssertionError at FileDetectorTest.java:45
org.zalando.intellij.swagger.file.FileDetectorTest > thatIsSwaggerJsonFileBasedOnFileName FAILED
    java.lang.AssertionError at FileDetectorTest.java:37
```

After they are fixed I'll merge.

2017-03-06 12:05 UTC, merged

2017-03-06 12:06 UTC, semonte commented
@manuc66 Thanks for the fix!